name: Submodule Auto Updater

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Nerinyan-WEB
      uses: actions/checkout@v2
      with:
        repository: 'Nerinyan/Nerinyan-WEB'
        token: ${{ secrets.PAT }}
        path: Nerinyan-WEB

    - name: Update Submodule
      run: |
        cd Nerinyan-WEB
        git submodule init
        git submodule update --remote
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git add src/i18n
        git commit -m "Update Nerinyan-i18n submodule"
        git push
